export type AppAction = 'read' | 'create' | 'update' | 'delete' | 'manage';

export type AppSubject =
  | 'Dashboard'
  | 'Company'
  | 'Account'
  | 'JournalEntry'
  | 'FiscalInvoice'
  | 'TaxAssessment'
  | 'TaxPayment'
  | 'Payroll'
  | 'Employee'
  | 'Asset'
  | 'Lalur'
  | 'Audit'
  | 'Report'
  | 'Obligation'
  | 'TaxUpdate'
  | 'Honorario'
  | 'ClientPortal'
  | 'EmployeePortal'
  | 'Cct'
  | 'Custo'
  | 'Protocolo'
  | 'Registro'
  | 'Administrar'
  | 'BuscaNfe'
  | 'Certificate'
  | 'QueueAdmin'
  | 'Settings'
  | 'all';
