import { Injectable, Logger } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { InjectQueue } from '@nestjs/bullmq';
import { Model } from 'mongoose';
import { Queue } from 'bullmq';
import { Cron } from '@nestjs/schedule';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { ObligationsService } from './obligations.service';
import { Company } from '../company/schemas/company.schema';
import { Invoice } from '../fiscal/schemas/invoice.schema';
import { tenantContext } from '../tenant/tenant.context';
import { QUEUE_NAMES } from '../queue/queue.constants';

/**
 * Scheduler para geracao automatica de obrigacoes acessorias.
 *
 * - Dia 1 as 4h: gera obrigacoes mensais do mes anterior
 * - Dia 2 de janeiro as 4h: gera obrigacoes anuais do ano anterior
 * - Dia 10 as 6h: verifica completude e auto-gera SPED quando pronto
 */
@Injectable()
export class ObligationsScheduler {
  private readonly logger = new Logger(ObligationsScheduler.name);

  constructor(
    @InjectModel(Company.name) private companyModel: Model<any>,
    @InjectModel('Invoice') private invoiceModel: Model<any>,
    private readonly obligationsService: ObligationsService,
    private readonly eventEmitter: EventEmitter2,
    @InjectQueue(QUEUE_NAMES.REPORT_GENERATION) private reportQueue: Queue,
  ) {}

  /**
   * Gera obrigacoes mensais para todas as empresas ativas.
   * Roda todo dia 1 as 4h — gera obrigacoes do mes anterior.
   */
  @Cron('0 4 1 * *')
  async handleMonthlyObligations() {
    this.logger.log('Gerando obrigacoes mensais automaticamente...');

    const now = new Date();
    const prevMonth = now.getMonth() === 0 ? 12 : now.getMonth();
    const prevYear = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear();

    const companies = await this.companyModel.find({ isActive: true });
    let generated = 0;

    for (const company of companies) {
      try {
        await tenantContext.run(
          { tenantId: company.tenantId.toString(), userId: 'system', role: 'Admin' },
          async () => {
            const results = await this.obligationsService.generateMonthlyObligations(
              company._id.toString(),
              prevYear,
              prevMonth,
            );
            generated += results.length;
          },
        );
      } catch (err) {
        this.logger.error(
          `Erro ao gerar obrigacoes mensais para ${company.razaoSocial}: ${err}`,
        );
      }
    }

    this.logger.log(`Obrigacoes mensais geradas: ${generated} para ${companies.length} empresas`);
  }

  /**
   * Gera obrigacoes anuais em janeiro.
   */
  @Cron('0 4 2 1 *')
  async handleAnnualObligations() {
    this.logger.log('Gerando obrigacoes anuais automaticamente...');

    const prevYear = new Date().getFullYear() - 1;
    const companies = await this.companyModel.find({ isActive: true });
    let generated = 0;

    for (const company of companies) {
      try {
        await tenantContext.run(
          { tenantId: company.tenantId.toString(), userId: 'system', role: 'Admin' },
          async () => {
            const results = await this.obligationsService.generateAnnualObligations(
              company._id.toString(),
              prevYear,
            );
            generated += results.length;
          },
        );
      } catch (err) {
        this.logger.error(
          `Erro ao gerar obrigacoes anuais para ${company.razaoSocial}: ${err}`,
        );
      }
    }

    this.logger.log(`Obrigacoes anuais geradas: ${generated} para ano ${prevYear}`);
  }

  /**
   * Verifica completude de dados e auto-gera SPED quando pronto.
   * Roda dia 10 as 6h — verifica se todos os dados do mes anterior estao completos.
   */
  @Cron('0 6 10 * *')
  async handleCompletenessCheck() {
    this.logger.log('Verificando completude para auto-geracao de SPED...');

    const now = new Date();
    const prevMonth = now.getMonth() === 0 ? 12 : now.getMonth();
    const prevYear = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear();

    const companies = await this.companyModel.find({ isActive: true });
    let autoGenerated = 0;

    for (const company of companies) {
      try {
        await tenantContext.run(
          { tenantId: company.tenantId.toString(), userId: 'system', role: 'Admin' },
          async () => {
            const companyId = company._id.toString();

            // Verificar se todas as NFs do periodo estao escrituradas
            const pendingInvoices = await this.invoiceModel.countDocuments({
              tenantId: company.tenantId,
              companyId: company._id,
              dataEmissao: {
                $gte: new Date(prevYear, prevMonth - 1, 1),
                $lte: new Date(prevYear, prevMonth, 0),
              },
              status: { $ne: 'escriturada' },
            });

            if (pendingInvoices > 0) {
              this.logger.debug(
                `Empresa ${company.razaoSocial}: ${pendingInvoices} NFs pendentes, pulando auto-geracao`,
              );
              return;
            }

            // Auto-gerar EFD se dados estao completos
            try {
              await this.obligationsService.generateEfd(companyId, prevYear, prevMonth);
              autoGenerated++;

              this.eventEmitter.emit('obligation.ready', {
                tenantId: company.tenantId.toString(),
                companyId,
                tipo: 'EFD',
                competencia: `${String(prevMonth).padStart(2, '0')}/${prevYear}`,
              });
            } catch {
              // EFD ja gerada ou erro — ignorar
            }
          },
        );
      } catch (err) {
        this.logger.error(`Erro na verificacao de completude: ${err}`);
      }
    }

    this.logger.log(`Auto-geracao SPED: ${autoGenerated} EFDs geradas`);
  }
}
